name: simple-voting-system
recipe: drupal11
config:
  webroot: web
  via: nginx
  database: postgres
  xdebug: "develop,debug"
services:
  database:
    portforward: 5433
  appserver:
    config:
      php: lando/php.ini
tooling:
  phpcs:
    service: appserver
    cmd: /app/vendor/bin/phpcs
  phpcbf:
    service: appserver
    cmd: /app/vendor/bin/phpcbf
