name: simple-voting-system
recipe: drupal11
config:
  webroot: web
  xdebug: true
  config:
    php: ./.lando/php-ini-overrides.ini
tooling:
  phpcs:
    service: appserver
    cmd: /app/vendor/bin/phpcs
  phpcbf:
    service: appserver
    cmd: /app/vendor/bin/phpcbf
