name: simple-voting-system
recipe: drupal11
config:
  webroot: web
  database: postgres
  xdebug: true
  config:
    php: lando/php.ini
services:
  database:
    portforward: 5433
tooling:
  phpcs:
    service: appserver
    cmd: /app/vendor/bin/phpcs
  phpcbf:
    service: appserver
    cmd: /app/vendor/bin/phpcbf
