<?php

/**
 * @file
 */

declare(strict_types=1);

/**
 * @file
 * Provides a question entity type.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function voting_system_theme(): array {
  return [
    'voting_system_question' => ['render element' => 'elements'],
    'voting_system_answer' => [
      'template' => 'voting-system-answer',
      'variables' => [
        'answers' => [],
      ],
    ],
  ];
}

/**
 * Prepares variables for question templates.
 *
 * Default template: voting-system-question.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the question information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_voting_system_question(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}
